export const AD_CATEGORIES = {
  SURF_CAMP: {
    id: "surf_camp",
    label: "Surf Camp",
    emoji: "🏄‍♂️",
    monthlyPrice: 500,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  SHAPER: {
    id: "shaper",
    label: "Surfboard Shaper",
    emoji: "🏄",
    monthlyPrice: 250,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  BEER: {
    id: "beer",
    label: "Beer",
    emoji: "🍺",
    monthlyPrice: 500,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  COFFEE_SHOP: {
    id: "coffee_shop",
    label: "Coffee Shop",
    emoji: "☕",
    monthlyPrice: 250,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  VIDEOGRAPHER: {
    id: "videographer",
    label: "Videographer",
    emoji: "🎥",
    monthlyPrice: 250,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  PHOTOGRAPHER: {
    id: "photographer",
    label: "Photographer",
    emoji: "📸",
    monthlyPrice: 250,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  INFLUENCER: {
    id: "influencer",
    label: "Influencer",
    emoji: "📱",
    monthlyPrice: 250,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
  CLOWN: {
    id: "clown",
    label: "Clown",
    emoji: "🤡",
    monthlyPrice: 250,
    fields: ["title", "websiteUrl"],
    adPosition: "sidebar",
  },
} as const;

export type AdCategory = keyof typeof AD_CATEGORIES;

export const GOOGLE_ADS_CONFIG = {
  dailyBudget: 23, // Combined daily budget from all contributions
  keywords: [
    "surfing south africa",
    "surf spots sa",
    "learn to surf",
    "surf gear",
    "surf equipment",
    "surf lessons",
    "surf camps",
    "surfboard shapers",
    "4x4 surf spots",
    "surf forecast",
    "surf travel",
    "surf travel south africa",
    "surf spots cape town",
    "surf spots transkei",
  ],
  location: "South Africa",
  language: "en",
} as const;
